### ISSUE TITLE
Help Wanted: Issue with the integration

### ISSUE THREAD

**Issue by Valoneria** [nodes-php/nemid#26]
When trying to get the iFrame to work, i keep getting a consistent APP001 error from the iFrame. I've verified that my parameters are fine through the developer site, and tried additional ways of including the parameters, to make sure i didn't malform them somewhere along the way. 

Is the Origin a necessity when using the iFrame, or do you know if it's a possible error with running it in a localhost environment?

**Comment by daliborgogic** [comment]
@Valoneria `APP001` is error while parsing the parameters by the NemID client library. 

Possible causes include:
- The parameters are not structured correctly (must be valid JSON for the JS client).
- A mandatory parameter is missing.
- An unsupported parameter was submitted
- [JS Client: The `ORIGIN` parameter does not match the actual origin.]
- An unsupported value was provided for an otherwise supported parameter.
- The calculated digest does not match the value submitted in the `PARAMS_DIGEST` parameter

`ORIGIN` is optional, but highly recommended. I'm getting the same error in both environments. Have you found what triggers the error?

**Comment by daliborgogic** [comment]
@Valoneria In my case problem is solved. Unix time is converted to string [#L62](https://github.com/daliborgogic/nemid/blob/master/index.js#L62)  now.

**Comment by Casperhr** [comment]
Feel free to PR updates to either code or readme
